version: '3.1'

networks:
  default:
    driver: bridge

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zumbee